### ISSUE TITLE
Table Export to CSV?

### ISSUE THREAD

**Issue by fishmichael** [shzlw/poli#21]
You can export a chart contents to CSV but not a table?  This project is 99% of what we need for some internal reporting, this would be the remaining 1%...

Great project, btw.  Been using ART (Another Reporting Tool), but your report creation process is much easier for end users.

**Comment by shzlw** [comment]
Thanks for using Poli! I just tried it  and I do see the export CSV button when I hover the cursor over the top right corner of the table widget. Could you try it and let me know it works for you? 

I checked the doc and it just mentions click the export button but not hover the cursor. I will fix that.

![csv_table_test](https://user-images.githubusercontent.com/4129280/61832917-b8053600-ae40-11e9-9330-ab74d5e0ab9e.jpg)

**Comment by fishmichael** [comment]
Zhonglu,

That is awesome.  I hadn't created a chart yet, so I thought that CSV export button was there (no hovering).  I did verify that I was able to find and select that button by hovering and then clicking the  CSV button.  

Selecting it seemed a little flakey with Chrome 75.0.3770.142 on Windows 10.  When you got close, the button would appear, but when you attempt to center over it, it disappears.  I just clicked in that area and it did download (quite quickly - nice!).

Is there a default setting somewhere for the filename that is generated?  Selecting the export downloads a file called csv with no extension.  Under Windows, that requires either locating the downloaded file and renaming it or selecting a program to open an unknown file type.

Thanks for your prompt reply!

Mike

**Comment by shzlw** [comment]
About the flakey problem, I tested it and I believe the cause is when the table has no title, the CSV button is kind of overlapping with the right edge of the table which triggers the column width adjustment event. I will take a look into that.

The CSV file name has a bug. If the component has no title, the file is supposed to be downloaded as  
poli.csv otherwise "component title".csv. There was another request asking for providing a pop up to edit the file name before export the file. I will add that dialog to fix this issue.

**Comment by fishmichael** [comment]
Verified that providing a title to the component resulted in an export to a file with the same name with a CSV extension.  Awesome.

**Comment by shzlw** [comment]
[v0.9.1](https://github.com/shzlw/poli/releases/tag/v0.9.1) is now released which contains the fixes for renaming CSV file and export CSV button.
